AWSTemplateFormatVersion: '2010-09-09'
Description: A beginning CloudFormation template to create a MySQL database and a Route53 HostedZone
Parameters:
  DatabaseName:
    Type: String
    Description: The name of the database you want to create.
  DatabaseMasterUser:
    Type: String
    Description: The master username for your database.
  DatabaseMasterPassword:
    Type: String
    NoEcho: true
    Description: The master password for your database.
  HostedZonePrefix:
    Type: String
    Description: The prefix to use for creating <prefix>.saas.slab.sytac.dev. Make sure no one else in the group is using this prefix.

Resources:
  sLabHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub
        - "${Prefix}.saas.slab.sytac.dev."
        - { Prefix: !Ref HostedZonePrefix }

  sLabDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Sub
        - "${DBName}-slab-db"
        - { DBName: !Ref DatabaseName }
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUserPassword: !Ref DatabaseMasterPassword
      MasterUsername: !Ref DatabaseMasterUser
      MultiAZ: true

Outputs:
  DatabaseUrl:
    Description: The url of the database.
    Value: !GetAtt sLabDatabase.Endpoint.Address
  DatabasePort:
    Description: The port of the database.
    Value: !GetAtt sLabDatabase.Endpoint.Port
